### ISSUE TITLE
some questions about uramdisk.image.gz

### ISSUE THREAD

**Issue by mazyi** [ucb-bar/fpga-images-zybo#1]
hello, I'm a student from China.
I try to make a linux on zybo but I don't know how to make uramdisk.image.gz.
Can u give me some suggestions or tutorials about the uramdisk.image.gz?
thx a lot.

**Comment by sbeamer** [comment]
Please refer to our main [fpga-zynq](https://github.com/ucb-bar/fpga-zynq) repository for concerns about the repo. This repo is a submodule of fpga-zynq and contains pre-built binaries.

Instructions for building uramdisk.image.gz (and more) are available in fpga-zynq's [README](https://github.com/ucb-bar/fpga-zynq#fromscratch).

**Comment by mazyi** [comment]
Thank you.
That repo helps me a lot of my graduation project!
